### ISSUE TITLE
The unauthenticated git protocol is no longer supported.

### ISSUE THREAD

**Issue by someoneinjd** [taoky/ustc-cas-mock#1]
根据 GitHub 的[这份公告](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git)，`git://` 形式的连接会失效，所以 `requirements.txt` 中的 `git+git://github.com/taoky/django-mama-cas@master#egg=django-mama-cas` 也会失效并在安装时报错，可以考虑修改为 `https://`

**Comment by taoky** [comment]
已修改。
